language: c
sudo: false
addons:
  apt:
    packages:
    - gfortran
before_install:
  - cd $TRAVIS_BUILD_DIR
  - mkdir ../progs
  - cd ../progs
  - export PROGS=$PWD
  - ./install-deps.sh $PROGS
script:
  - source ~/.bashrc
