language: c
sudo: required
env:
  global:
    secure: "Mip85ZPbkKWJv+yb5t5kJAlPp1k7ji0u5HiwSqJu/WveilctXsYQMDp+fUKPGC8VYLBcEsWvofd4ls12Stc28+zYMObiiQUcCk1JUda8laMoHAFzUKApy1EuY4X2yiWUg62nyysN6eQAOAb4061dvflIXTYQ5/tfobm/g4gVnn6ijchVtZMhKx6EbZ9xqAoQ2PZ9tGDpsWJgirzlVtC8o7MRDls4hOXekdXwCODfuG1tNTZCZ/Y8tzwh1m+SECqnAE9GyThUQoEEKvX/8JClUU9h36ZBNbolp+3LHnOZzeXIEgkR71a91A5Y4GLOmtwYLI3EwnYqOuOkv5IOzH0lPJqcFPqP6RGDa/+pd9CNFCMGvTILeucSkAE6lB8n8F5GtFzbH5WlWZKlMyLwVLa7+LtMn897poPfKtuR2UvPjWLNlytRa5vFgNgMSerb90NcyVw9cNwbzaw3C1rKvUN6XwzalvPgj4vfEQxek60c7FLfdvICp5EMDSvE/edS5+bhpETtiaPukc/JBO46GEB0g3BkEYWgY8yquKcUkrZx42Yc5Lk/vZl3whW/TAGdig6/un0jSik9TbgLSQa4sHxAbd5DNQhOuKHVKeQ/RdGTCbd1kpssSfm22s+dRpp1ex0SIQJ0adNTqjb4iWghU3VO/o0kY8SgBQqvlR8ykSe6DpE="
    secure: "EIDNIQINr4UnoO1GMrzNjjp1O3n1g7+3Z0n4Z9eRmYppB49+jgUiQMdTZw/D9jMmomzRs5ZjRP2v4frIylL4gNsoBZZgUCahAzS49vG9pQfl4tp1AumvK/IlmZAAm06spwTIssv9bcg0/E1SiY6VMWV8+uMjJOhYA2Z5ucdKAt9KKL/yRHAInheNOwWs8aELNZpIlmMoUxRWJnFqwKPbml416F+K3P4thZj2wZNu3uJVjrXrQSJ1OyOXaIkDBafkD0Cg1cxg8ZsqRTEOPdycETOqX5QV8DbAwFWGrl2280EFGxlgqCoXfzh3NALDMciPfTeAdz3C5g6vDekjVRB5k8h+twa9I21SULRlSHmXWwukjHOtClncEBE1nyUajCEaMvXtmRa8HJM1pgxv25P3LsZBTU9LPJb7hgK9d2UuX2FiKruo5cN6ckvjvObr8VRwEqpsj5cnXeNmWEtCECAgl/Gn3cmyn24tRSv+jLaWP80xOT/Pk2lLu4MNhZpkV0a8pfNTBioE4+vtU7rEIcG6/QZ3vKVXqzHzoYgGonrMkNq6402Sn2A3DDgXmumC+QW+S5MxZsKipk98t4Z9cv+MQ5T5ddOuIOTSFIvM4BJrc09r1yKSo0M3+HFQXvwYog1KMhnWx+oyoScgE5yqle8lnjspppO2yMsXUJFGumTbsIU="
    secure: "A6zjceQBBp2r/fsMvEnlur4Jxkon46O02O2NpYf4EUtsS5gHV8HccR07x18hYQ5c5wnttZEPTqMH0yNtK6G0IEbhjqgq8KIMhQ4amdtnhDOpcUiPKqSK5tyK5ml67nto0pXYCc9hyrVmcdUmnNK00+0vgDcGScAllDyYw8yMnkWImpDF4UvIbZIJ32xbWe+/ybgguxwfxhwmn7wy1IY0aAeDmpMO3D24Xq4gM5vAutwTBXjBEbbD4N+t8Yes92Vs68ywsCM9fr63p24QRTnWU+ueAKYDHdZhh11TmoM1kkRVmdSSH7XW8gyy66PsfDiN73Yk+BLruzDM74vl3PlP9ly5OXAycAt/mWwoYZlKyb2ESPXv0AvC6iYnm8l88h3o6DgObuqytERDrG2pZubi4YADtYtSIw+3sNTyWgfFbNMecpXxIx82/suG7XLNge/Absa3tBtPSawHxKNeUD6Fv7iJaGHlREBEsYduJ8da/KcT3P1dSDxH1NIl26yMSHcdjpOOd7y0sHoQh17PJayHOROup+Y+fw5qil4ph1FrndeM47LYXBgvbqfZmwGZR55PfbTgL5B1crfbfMyRzCZdFXGy5yAGScGo3h0eupdZGGMvL81dyd4PoWjdoRKBTlWIVF2VitkNkJVPBWpS/5F7Ac5Na9XiaKJ16pPmRft6T1s="
addons:
  apt:
    packages:
    - gfortran
    - csh
before_install:
- cd $TRAVIS_BUILD_DIR
- mkdir ../progs
- cd ../progs
- export PROGS=$PWD
- cd -
- ./install-deps.sh $PROGS
- ./install-test.sh $PROGS $OCN_LINK $RTM_LINK $WAV_LINK
script:
- source $PROGS/env_progs
- ./bootstrap.sh
- ./configure --prefix=$TRAVIS_BUILD_DIR --with-atm=$PROGS/atm --with-ocn=$PROGS/ocn/Build
  --with-rtm=$PROGS/rtm --with-wav=$PROGS/wav/obj
- make
- make install
