language: c
sudo: required
env:
  global:
    secure: "VNAG9p2OPvWdeyTA91py/mHcGs6Dvpc+vvdPd1QK/lJsFEFeQdahuYW86BqpQEWbTlGqyJifK9di/xMoJ31ZH0omtukTb8pgKrqQaVKvmLLUoCzcXem46mZBBdYc0uMzIaxsfkbmf+bcBi8eSTx2nqamc8rJD+iT97akmTmlJe0NyKgFmHs0v6vfXfOZiEj6WhGdud9ky7EsPnpXEkuelz5qLWzZkDuPYPrho/INNg9cPuqfoX6+7ENrETrtcwDRpQnnWp2qjyQWK0hfVnilXlj9M4JYxMQSWKTw067FdlgGbrxW5KpeXG8Amd3+TYdTSkr+LxhDnggg8r5oXHwNMbbWP0pxWJnnE8Z0Bdjsu0pSQwLNIHEELnFn+MQq0WpZ+fK/0nVp1s7HFd9vIwHffEP5eBcbVx5HNPOjsG19XpFV2DMQBJ/sB1JvoEA6ov8zM61D0Ckw6krCPwlme0FxBPqNEPx5LmyoVn9H9klOl1sLsIqgwo67wiK/ObmtzHjhBZBuu4Ak01PWZcrB+ET8bdTXyoZN20+/Wjhe43/3KcGUcjEOvnp2P6Nohx5md6+V98JAHQEqZCDLQuSY91wIEojBy2FzVPSpMXeQ8mVFbPAR8PvfgHSgpC0h7NkLvEFuFHVi9cacd5ZkTgH9ylYuMtyUFgEX0MAgMMm6nEf8W4k="
    secure: "sMczfkDIN+TsplsWq8cNxvMjo+hnX5mQdcAgqWvPF7CYdkgdLoCeZ+nM4NE6qI9PxLyYIqd01BQnNUYgJkqQggBrDwKV3mcyhPqdSFO2Ans+/ntPoTHl3VwsFLB2/YWJ0vNUKOR5LV0OZHUOTMtiXhrkGNfpxWkMxskbhOLOy1pW6xEow+gkklrJvXZ3ECBNqYc//OKhwPmn+8tWC0PsX/Kih2R0bo3t4C8dNz+HUF36v10pttxCemV8IBPN94Yxms/YlQL5Nb27QWM5UdSyV+RD9d5VFWYBq6/cRKogS7eI1EQn8UkorlMXC+BixkcjVifpmFg/qf4x057Bm7uDDx2jT7M13QoCNzL48eow5v4EpdsfnebKOP1HjbVmz2SY9w8Yn0ttuehPpE1vwg+FijWMnkMhM7LDwSAnmESTUipx4cor0RGZJ3je8dwMviXP8Hxd6KYc1yOPjCbAPi3hyZ6Bad2Rg9P43Vhca01yLQttYsqjndbs9S2jrZpA53b7wDKTQNKpUZNAYQKCgvTPNmHqum90veeJpD/hG0D+Zb5KAsypbKX3CBzZyDdh4QapAVilo6MpJWN2tqhbAIGibe+h2d17IxdsfcCEVaVIubgKSK7X823pljtXDVRQFwpbRgJDAdOD5UnsCv8vhFM1iuFztAckyL+alLekCl85aKA="
    secure: "hewzBzNcZThQhO8zZ8QbBOn2yoVqsV3l39wi7/yDTwScI5O2cgv+5LzLNkT0WAFgindl0qUL/QIC/ZMfx3JHg8iMNwOSWa6v8/TVKC0CnK/OOYvw7iJqKaZY0Kuy/EZvvXSiDb/RS/5Ci4IGSGn4l9uS4aIlYIDNMNwou5P6ubKRHg6bG0/PzlL5tBgi+s44gngHAXjvGfyKGzum7yxVU2k7RJPQbRwBH9FwRh4iX1ryR9yzu1MCSV13qHc0eqFQSp4azJ4MknHj7WHgDvH2pWfuJU0tnm+UZ5vCJhygnu0IXt8nAGweBNglpyUjTAE+asuaZEh7NW8uFIQiEMyueNX5dp0aEhTDAKJbRQ6IuGsTEfnd0+8w4lUqK8pFvHjHuZjH9VBV7CbpnwoIHCWnNiffrJLqeyNmh3MjQjk37HzNI/AlNtMO9msU9LSC4hYYMU0qQJc+lGHSVNCdRzjHOOD3wIM4NddC6RuDS/lr+hWQnlblB7+7DWIJFkLE+Jpllah2iI27ermGuh1kG3h+5T0CbKlPItLiHgOv67XGgRVZ0nBK5q4NyIKPI2ua6XNP18KIvxUxVcx5VHY0IP6bFLAumnefmvWm8bWbfLBzHPIasaaq47PgBxJS8WNScdpNNYCIXOsyFGnoWVbGszTlxqOQyubgJ0cvs7q9Nrot4Q0="
addons:
  apt:
    packages:
    - gfortran
    - csh
before_install:
- cd $TRAVIS_BUILD_DIR
- mkdir ../progs
- cd ../progs
- export PROGS=$PWD
- cd -
- ./install-deps.sh $PROGS
- ./install-test.sh $PROGS $OCN_LINK $RTM_LINK $WAV_LINK
script:
- source $PROGS/env_progs
- ./bootstrap.sh
- ./configure --prefix=$TRAVIS_BUILD_DIR --with-atm=$PROGS/atm --with-ocn=$PROGS/ocn/Build
  --with-rtm=$PROGS/rtm --with-wav=$PROGS/wav/obj
- make
- make install
