language: c
sudo: required
env:
  global:
    - secure: "VsqWigdXeDwa2hdm5WuZ9adyiRfEvoAFGNzuIqVij1ZN0p9IBy6xIXVD8XG3t890muL93CRAOw8EYKmWFpWIhrLCN6L2B6A9+TBMDrKa7gwWpRyBZLSlUNwWgQ9XuDonkkxpAfFTkQGR9wPgh1Rf02kRgBL1q5j9tDcbFOZ6WSQXcXSusn6SJney/ZNPO0lhUUk/5T5H9pX6SYtHIZF6giDKQU0lPD2gLBDlKaOMUjni731E0F9d5t2bH2gwGRsYYEQONR8+4c4RKawGczmrdPUoPHHISB0iY/RSCB7TN2B4LcDRrRT0TJAu5r4J+kDeUQppkCHrcA2ARa5o7Z1NSjgnOP79Kf4VfK3ZasUkDVDJtY1hgmeIVbtZhi8Lf6Df/xu4bZ5JA7PvbmgjeSpEByIl/zPzYI2nmc2WfTVpuapdLTkdlcS8bwkTR16Hl7o+xjAsRmzpP/4rYlZGJab8EE1i8RUM7FqKdC0ij3rb25lvv64cH70e0UJii/yCNlDoPy/xUZQA9jj7ypJrCbI1NpgtRrxo3Y4dYLc4jtCjhE0e+69o+pMEEuaXHfTViG3eBv2aBNEP+Rl3ZpZ+UNZitby70YDcisMX9o7P1CKrCFEEbCiiyrHataUQB+2xkztzou9+pG/k+KLh5ZXOgZhvPkevcS4qWoCdOjG384xC+Uw="
    - secure: "DMgeddUuIxzh9j2fXK21ZS18Nr/4m4cR6eAoVoO60JBSbQcNsJ5BplzP2p6Tkb3wRPte0/DWpzidZY+NAUrSOa27Pcn6/GzXdAiWy81qua36koGhtkNnuSEZvF/IO3FAIRFTAs8b3UC0H2N0QkGnC7PrlIkySDFmFwZnodthzJ7SiVpTbNCkFbP7vcB1Jw+LazC05pznLFiWj/YOzM2wUfD0qW+dtzZ6xGOC9YGat0XZjnCPGJAhyTnGix0IyS0cRW1XABJCn9dMQR8HKsb262SbGXmbkNc/nC4ybJarfi/vevz898Sg9mvICD6PFrZA/8ujrhwlPcHjqhjhdH8cVf4YYXGUR/qbGoFRyxyqi3VtiqanclqlQEYfn1grXTDKiUaldmmUynEuDvh/1WI6ZWEGAHnRG43HdCvUONj93Vj4ZxENYKayvLv0ua/GnAgavRIzyBofY1s9QR4DO0/1k2syD0GhT8YAEKINQYktgGrDBb5vZ1NkoINWyD/z32BzXZrZScA0w5+0OdVmniAOJGcDaRPA7MB+lSp3IKBLfwGqSXEK4o/QRPY6dqMlbjdsoSMy8duVxbqIPLq6uD/D8rJyLGvxS9XcPPpQRQrkJMAo3KUVjmTuth1YSWF1oYpqHPs1ww4Aa4JCznDXnqn13I2lOYpphlzSxsf7e0vLgbs="
    - secure: "d6N/4KodnZD6uV1b5imeBNpS95joqrvmUSqmoSj6oekNyNBkB/SYBv8RgnNQRoCZ6q3rBn0gcgdzebM+F8SXIE1PwjhZoom8/lIknBrsMu8m7dP9kmeV33g2nJgblQTi8LErFTcgYanlN09VSajCz/izuLw9bzy5VnWOxYXrEEiG1dUbOKDdGnXA+LemMdSsoxNxGDiS9Ic59tH0VlrTfBpPWo4zahncr5ENqjeedDHmC3wYMT8PU2yz8QJe3XIiDP9Hg2qNR0iFR33R2CRRrf5ErhZywlu08ANHkLFP0ns/buTC1CBs9W+QoV2O0TXoYSLlkLMnYmw8d1lt6JU1q+1nuZeaUcF/n0ZMDgq2t444RaPHoOdPX2HRgrw6ru6thSCS7rsPs0r7300Y2w+NFY41EHAfFejN8esNuuJl4t0odiKn2C6GsW8M7/i/B3U/rH/+vZAXLZlzXFipH7F/Gp5qAVecikOFYcWGCxHGu3nap3dCgVeW3gziypLswE6VyG2uVGZJ9ev4jAln76iNMwvgS+CewP7kdbkLzG9a2mRpKz77j401uKqRePfdB3zvy4ZloBEUGM1PBRyPWisStSWz5+wOazbwVCsuECipDN3jPCNJjRRsGgkbiuLHNEuxzf5b0yXnic7GmmjuR9xxZpONKBnlyCKx+eVuktKiG/w="
addons:
  apt:
    packages:
    - gfortran
    - csh
before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y subversion
  - cd $TRAVIS_BUILD_DIR
  - mkdir ../progs
  - cd ../progs
  - export PROGS=$PWD
  - cd -
  - ./install-deps.sh $PROGS $OCN_LINK $RTM_LINK $WAV_LINK
script:
  - source ~/.bashrc
  - ./bootstrap.sh
  - ./configure --prefix=$TRAVIS_BUILD_DIR --with-atm=$PROGS/atm --with-ocn=$PROGS/ocn/Build --with-rtm=$PROGS/rtm --with-wav=$PROGS/wav/obj
  - make
  - make install
